language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.22.0

before_install:
  - docker --version
  - mkdir -p "$HOME/bin";
  - export PATH="$HOME/bin:$PATH";
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > "$HOME/bin/docker-compose";
  - chmod +x "$HOME/bin/docker-compose";
  - sudo $HOME/bin/docker-compose --version
  - sudo mkdir -p /usr/local/tomcat/conf/radar/
  - ./gradlew downloadApplicationDependencies

script:
  - ./gradlew check
  - ./gradlew integrationTest